### ISSUE TITLE
Uncaught DOMException on myApp.set("playing",true);

### ISSUE THREAD

**Issue by kjetisve** [23/GlueFrame#6]
Tried using GlueFrame to start player from JS.
Got set(currentTime, t) working, but set("playing",true) gives me this error:

player.js:487 Uncaught (in promise) DOMException
Eingebaut.$this.setPlaying @ player.js:487
(anonymous) @ player.js:562
Glue.$this.set @ player.js:35
Glue.$this.receiveMessage @ player.js:37

Code:
http://jsfiddle.net/xr2of98y/2/

**Comment by steffentchr** [comment]
Hi Kjetil, 

This is caused by the auto-play policies in Chrome and Safari: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
Short version, you're not allow to play back video with audio automatically. Rather, it requires user interaction. You may want to use the `mutedAutoPlay=1` option (available in TwentyThree players built within the last ~3 months) when embedding the player. This will start playback muted and allow users to turn on sound.

Steffen
