### ISSUE TITLE
Uncaught ReferenceError: GlueFrame is not defined

### ISSUE THREAD

**Issue by connectaryal** [23/GlueFrame#8]
Despite installing the GlueFrame npm package cannot access API methods.
Codepen - https://codepen.io/connectaryal/pen/dyWZMwJ

**Comment by steffentchr** [comment]
@connectaryal In the Codepen example, I don't think dependencies are loaded because of their response content-type. At least I'm getting a bunch of errors in the browser console when looking there.

**Comment by shivaaryal-webo** [comment]
@steffentchr As per the documentation, only the glueframe src link is required. Do we need any other dependencies?

**Comment by connectaryal** [comment]
@steffentchr As per the documentation, Only the glueframe src is required, Is there any other dependecies? I have tried on my local machine and still not working.

**Comment by steffentchr** [comment]
@connectaryal Based on the issue title here, I guess you're looking to load the library correctly -- because if you're seeing `GlueFrame is not defined` then you need to look at loading of the glueframe code.

As noted, I haven't been able to run your codepen example, but looking at the code itself, you should make sure to use `"Player"` instead of the lower-case version when doing `new GlueFrame(...)`.

**Comment by connectaryal** [comment]
Yeah, I have tested it too but still not working.

**Comment by AVTPJ** [comment]
I managed to get your pen working by removing the direct link to the js library and adding it from NPM.

Note: It seems to reference the class wrong:
`import glueframe from "https://cdn.skypack.dev/glueframe@1.1.2";`

Had to manually change it to:
`import GlueFrame from "https://cdn.skypack.dev/glueframe@1.1.2";`

See my pen: https://codepen.io/avtconnect/pen/xxzVBbM
